Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pytube
yt = pytube.YouTube('https://www.youtube.com/watch?v=P4IrAXbpeyI') # kreiramo instanco objekta (kaj to točno pomeni, spoznamo pozneje)
yt.streams.get_highest_resolution().download() #Prenesemo video
------------------


[31m---------------------------------------------------------------------------[39m
[31mHTTPError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[61][39m[32m, line 3[39m
[32m      1[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mpytube[39;00m
[32m      2[39m yt = pytube.YouTube([33m'[39m[33mhttps://www.youtube.com/watch?v=P4IrAXbpeyI[39m[33m'[39m) [38;5;66;03m# kreiramo instanco objekta (kaj to točno pomeni, spoznamo pozneje)[39;00m
[32m----> [39m[32m3[39m [43myt[49m[43m.[49m[43mstreams[49m.get_highest_resolution().download() [38;5;66;03m#Prenesemo video[39;00m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\__main__.py:296[39m, in [36mYouTube.streams[39m[34m(self)[39m
[32m    291[39m [38;5;250m[39m[33;03m"""Interface to query both adaptive (DASH) and progressive streams.[39;00m
[32m    292[39m 
[32m    293[39m [33;03m:rtype: :class:`StreamQuery <StreamQuery>`.[39;00m
[32m    294[39m [33;03m"""[39;00m
[32m    295[39m [38;5;28mself[39m.check_availability()
[32m--> [39m[32m296[39m [38;5;28;01mreturn[39;00m StreamQuery([38;5;28;43mself[39;49m[43m.[49m[43mfmt_streams[49m)

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\__main__.py:176[39m, in [36mYouTube.fmt_streams[39m[34m(self)[39m
[32m    172[39m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m._fmt_streams
[32m    174[39m [38;5;28mself[39m._fmt_streams = []
[32m--> [39m[32m176[39m stream_manifest = extract.apply_descrambler([38;5;28;43mself[39;49m[43m.[49m[43mstreaming_data[49m)
[32m    178[39m [38;5;66;03m# If the cached js doesn't work, try fetching a new js file[39;00m
[32m    179[39m [38;5;66;03m# https://github.com/pytube/pytube/issues/1054[39;00m
[32m    180[39m [38;5;28;01mtry[39;00m:

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\__main__.py:157[39m, in [36mYouTube.streaming_data[39m[34m(self)[39m
[32m    154[39m [38;5;129m@property[39m
[32m    155[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mstreaming_data[39m([38;5;28mself[39m):
[32m    156[39m [38;5;250m    [39m[33;03m"""Return streamingData from video info."""[39;00m
[32m--> [39m[32m157[39m     [38;5;28;01mif[39;00m [33m'[39m[33mstreamingData[39m[33m'[39m [38;5;129;01min[39;00m [38;5;28;43mself[39;49m[43m.[49m[43mvid_info[49m:
[32m    158[39m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m.vid_info[[33m'[39m[33mstreamingData[39m[33m'[39m]
[32m    159[39m     [38;5;28;01melse[39;00m:

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\__main__.py:246[39m, in [36mYouTube.vid_info[39m[34m(self)[39m
[32m    242[39m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m._vid_info
[32m    244[39m innertube = InnerTube(use_oauth=[38;5;28mself[39m.use_oauth, allow_cache=[38;5;28mself[39m.allow_oauth_cache)
[32m--> [39m[32m246[39m innertube_response = [43minnertube[49m[43m.[49m[43mplayer[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43mvideo_id[49m[43m)[49m
[32m    247[39m [38;5;28mself[39m._vid_info = innertube_response
[32m    248[39m [38;5;28;01mreturn[39;00m [38;5;28mself[39m._vid_info

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\innertube.py:448[39m, in [36mInnerTube.player[39m[34m(self, video_id)[39m
[32m    444[39m query = {
[32m    445[39m     [33m'[39m[33mvideoId[39m[33m'[39m: video_id,
[32m    446[39m }
[32m    447[39m query.update([38;5;28mself[39m.base_params)
[32m--> [39m[32m448[39m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43m_call_api[49m[43m([49m[43mendpoint[49m[43m,[49m[43m [49m[43mquery[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m.[49m[43mbase_data[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\innertube.py:390[39m, in [36mInnerTube._call_api[39m[34m(self, endpoint, query, data)[39m
[32m    386[39m         headers[[33m'[39m[33mAuthorization[39m[33m'[39m] = [33mf[39m[33m'[39m[33mBearer [39m[38;5;132;01m{[39;00m[38;5;28mself[39m.access_token[38;5;132;01m}[39;00m[33m'[39m
[32m    388[39m headers.update([38;5;28mself[39m.header)
[32m--> [39m[32m390[39m response = [43mrequest[49m[43m.[49m[43m_execute_request[49m[43m([49m
[32m    391[39m [43m    [49m[43mendpoint_url[49m[43m,[49m
[32m    392[39m [43m    [49m[33;43m'[39;49m[33;43mPOST[39;49m[33;43m'[39;49m[43m,[49m
[32m    393[39m [43m    [49m[43mheaders[49m[43m=[49m[43mheaders[49m[43m,[49m
[32m    394[39m [43m    [49m[43mdata[49m[43m=[49m[43mdata[49m
[32m    395[39m [43m[49m[43m)[49m
[32m    396[39m [38;5;28;01mreturn[39;00m json.loads(response.read())

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\request.py:37[39m, in [36m_execute_request[39m[34m(url, method, headers, data, timeout)[39m
[32m     35[39m [38;5;28;01melse[39;00m:
[32m     36[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33m"[39m[33mInvalid URL[39m[33m"[39m)
[32m---> [39m[32m37[39m [38;5;28;01mreturn[39;00m [43murlopen[49m[43m([49m[43mrequest[49m[43m,[49m[43m [49m[43mtimeout[49m[43m=[49m[43mtimeout[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:215[39m, in [36murlopen[39m[34m(url, data, timeout, cafile, capath, cadefault, context)[39m
[32m    213[39m [38;5;28;01melse[39;00m:
[32m    214[39m     opener = _opener
[32m--> [39m[32m215[39m [38;5;28;01mreturn[39;00m [43mopener[49m[43m.[49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:521[39m, in [36mOpenerDirector.open[39m[34m(self, fullurl, data, timeout)[39m
[32m    519[39m [38;5;28;01mfor[39;00m processor [38;5;129;01min[39;00m [38;5;28mself[39m.process_response.get(protocol, []):
[32m    520[39m     meth = [38;5;28mgetattr[39m(processor, meth_name)
[32m--> [39m[32m521[39m     response = [43mmeth[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mresponse[49m[43m)[49m
[32m    523[39m [38;5;28;01mreturn[39;00m response

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:630[39m, in [36mHTTPErrorProcessor.http_response[39m[34m(self, request, response)[39m
[32m    627[39m [38;5;66;03m# According to RFC 2616, "2xx" code indicates that the client's[39;00m
[32m    628[39m [38;5;66;03m# request was successfully received, understood, and accepted.[39;00m
[32m    629[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([32m200[39m <= code < [32m300[39m):
[32m--> [39m[32m630[39m     response = [38;5;28;43mself[39;49m[43m.[49m[43mparent[49m[43m.[49m[43merror[49m[43m([49m
[32m    631[39m [43m        [49m[33;43m'[39;49m[33;43mhttp[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[43mrequest[49m[43m,[49m[43m [49m[43mresponse[49m[43m,[49m[43m [49m[43mcode[49m[43m,[49m[43m [49m[43mmsg[49m[43m,[49m[43m [49m[43mhdrs[49m[43m)[49m
[32m    633[39m [38;5;28;01mreturn[39;00m response

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:559[39m, in [36mOpenerDirector.error[39m[34m(self, proto, *args)[39m
[32m    557[39m [38;5;28;01mif[39;00m http_err:
[32m    558[39m     args = ([38;5;28mdict[39m, [33m'[39m[33mdefault[39m[33m'[39m, [33m'[39m[33mhttp_error_default[39m[33m'[39m) + orig_args
[32m--> [39m[32m559[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43m_call_chain[49m[43m([49m[43m*[49m[43margs[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:492[39m, in [36mOpenerDirector._call_chain[39m[34m(self, chain, kind, meth_name, *args)[39m
[32m    490[39m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[32m    491[39m     func = [38;5;28mgetattr[39m(handler, meth_name)
[32m--> [39m[32m492[39m     result = [43mfunc[49m[43m([49m[43m*[49m[43margs[49m[43m)[49m
[32m    493[39m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m    494[39m         [38;5;28;01mreturn[39;00m result

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:639[39m, in [36mHTTPDefaultErrorHandler.http_error_default[39m[34m(self, req, fp, code, msg, hdrs)[39m
[32m    638[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mhttp_error_default[39m([38;5;28mself[39m, req, fp, code, msg, hdrs):
[32m--> [39m[32m639[39m     [38;5;28;01mraise[39;00m HTTPError(req.full_url, code, msg, hdrs, fp)

[31mHTTPError[39m: HTTP Error 400: Bad Request

