Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xint = np.linspace(np.min(x), np.max(x), 50)
yint = np.asarray([kubicni_zlepki(k, x, y, _, k0, kn) for _ in xint])
plt.plot(x, y, 'ro')
plt.plot(xint, yint, label='Naravni kubični zlepek')
plt.legend();
------------------


[31m---------------------------------------------------------------------------[39m
[31mIndexError[39m                                Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[12][39m[32m, line 2[39m
[32m      1[39m xint = np.linspace(np.min(x), np.max(x), [32m50[39m)
[32m----> [39m[32m2[39m yint = np.asarray([[43mkubicni_zlepki[49m[43m([49m[43mk[49m[43m,[49m[43m [49m[43mx[49m[43m,[49m[43m [49m[43my[49m[43m,[49m[43m [49m[43m_[49m[43m,[49m[43m [49m[43mk0[49m[43m,[49m[43m [49m[43mkn[49m[43m)[49m [38;5;28;01mfor[39;00m _ [38;5;129;01min[39;00m xint])
[32m      3[39m plt.plot(x, y, [33m'[39m[33mro[39m[33m'[39m)
[32m      4[39m plt.plot(xint, yint, label=[33m'[39m[33mNaravni kubični zlepek[39m[33m'[39m)

[36mCell[39m[36m [39m[32mIn[10][39m[32m, line 19[39m, in [36mkubicni_zlepki[39m[34m(k, x, y, x_najdi, k0, kn)[39m
[32m     17[39m [38;5;28;01mif[39;00m i >= [38;5;28mlen[39m(k)-[32m1[39m:
[32m     18[39m     i = [38;5;28mlen[39m(k)-[32m2[39m
[32m---> [39m[32m19[39m out = ((x_najdi - [43mx[49m[43m[[49m[43mi[49m[43m+[49m[32;43m1[39;49m[43m][49m)**[32m3[39m/h - (x_najdi - x[i+[32m1[39m])*h)*k[i]/[32m6.0[39m \
[32m     20[39m     - ((x_najdi - x[i])**[32m3[39m/h - (x_najdi - x[i])*h)*k[i+[32m1[39m]/[32m6.0[39m \
[32m     21[39m     + (y[i]*(x_najdi - x[i+[32m1[39m]) \
[32m     22[39m     - y[i+[32m1[39m]*(x_najdi - x[i]))/h
[32m     23[39m [38;5;28;01mreturn[39;00m out

[31mIndexError[39m: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

